theme: jekyll-theme-slate
title: Andrew Jones 
description: <a href="https://andrew-jones657.github.io/" style="color: black; text-decoration: underline;text-decoration-style: dotted;> Home </a>  &nbsp; <a href="https://andrew-jones657.github.io/Blog"> Blog </a> &nbsp;  <a href="https://andrew-jones657.github.io/Projects"> Projects </a> &nbsp; <a href="https://andrew-jones657.github.io/Tutorials"> Tutorials </a> &nbsp; <a href="https://andrew-jones657.github.io/Gallery"> Map Gallery </a> 
google_analytics: G-KEPNKDPP7J
